### PR TITLE
HACS compatibility

### PR DESCRIPTION
**Pull request by nox10**
https://hacs.xyz

### CODE REVIEW

**Comment by cliffordwhansen** [comment]
@nox10 I love this idea, it means we will be able to click a button to install/update the component ;-), just not sure it fits well into HACS, I only say this as to get this integration working you need to "root" the gateway device (or at least I did), and that is not very user focused. #provemewrong ;-)

**Comment by aburghelea** [comment]
@nox10 I would love to have this implemented. (Actually have a fork just for this) + restoe of sensors. 

@cliffordwhansen #tryingtoproveyouwrong the fact that a complete integration has a steps  that is clearly more difficult to achieve than updating should not be a blocker in simplying the other steps. For example, I rooted the gateway for a "not so techy" friend . The poor guy can easily click an update buton, but doing it in a "manual" way  has a big chance in generating a "here's dude, i need your help". Now if we look at the general direction of HA , where they move in the direction of UI centered management and setup, i'd say that at least a custom HACS repo is a good place for this project. 

@cadavre what would you say ?:D

**Comment by cadavre** [comment]
I believe this is a good idea. Nevertheless I'm not maintaining this repository anymore as I'm not using Mi Gateway and I don't really want to let you down with updates.

The question is – do you @nox10 @aburghelea maybe would like to keep your forks more-up-to-date and provide HACS integration? :)

**Comment by cliffordwhansen** [comment]
@cadavre I installed this via hacs using @nox10's branch and it worked fine (I did copy the latest files over before restarting HA)

@nox10 Please bring your branch upto date with the latest changes :smile:

@aburghelea You proved me wrong, and I'm using it :stuck_out_tongue_winking_eye:

**Comment by aburghelea** [comment]
@cliffordwhansen 
I'll try to update my branch with the latest mods from here and my boolean restore params in the next few days.

@cadavre would you consider making me , and maybe @nox10 (if he wishes two) contributors to this repo ? Your repo is better know online than our forks :)) so we could keep it up to date. ?

**Comment by cadavre** [comment]
@aburghelea this is a good idea, if you say so.

After merging this repo and making it hacs-able – we can start tracking versions with releases.

**Comment by aburghelea** [comment]
Hey @cadavre @cliffordwhansen  @nox10 .
I've opened https://github.com/cadavre/miio_gateway/pull/24 for the same use case. If it looks good to you, I will merge it and close this one.

**Comment by StreamSage** [comment]
Fine for me.

**Comment by aburghelea** [comment]
Closing in favour of #24  and #25

**Pull request closed without merging**
